version: "{build}"

os: Windows Server 2012 R2

install:
  - choco install atom

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - %LOCALAPPDATA%\atom\bin\apm clean
  - %LOCALAPPDATA%\atom\bin\apm install
  - %LOCALAPPDATA%\atom\bin\apm test

test: off

deploy: off
